### ISSUE TITLE
No registered Auth Providers

### ISSUE THREAD

**Issue by vsavic** [wwwlicious/servicestack-authentication-identityserver#13]
I'm trying to run this identity server auth with core, but when I add `[Authenticate]` attribute and try to invoke my method, I'm getting this as response:
```
{
  "responseStatus": {
    "errorCode": "Exception",
    "message": "No registered Auth Providers found matching any provider"
  }
}
```

**Comment by stuartbfs** [comment]
Try :

[Authenticate(IdentityServerAuthProvider.Name)]

**Comment by vsavic** [comment]
When I change it to that, I'm getting:
```

{
  "responseStatus": {
    "errorCode": "Exception",
    "message": "No registered Auth Providers found matching IdentityServer provider"
  }
}
```

**Comment by stuartbfs** [comment]
Can you provide your configuration setup?

**Comment by vsavic** [comment]
Here you go:

```csharp
public class Startup
{
	//...
	public override void Configure(Container container)
	{
		//...
		Plugins.Add(new IdentityServerAuthFeature
		  {
			AuthProviderType = IdentityServerAuthProviderType.UserAuthProvider,
			AuthRealm = AppSettings.Get<IdentityServer>("IdentityServer").Url, // The URL of the IdentityServer instance
			ClientId = AppSettings.Get<IdentityServer>("IdentityServer").ClientId, // The Client Identifier so that IdentityServer can identify the service
			ClientSecret = AppSettings.Get<IdentityServer>("IdentityServer").ClientSecret, // The Client Secret so that IdentityServer can authorize the service
			Scopes = "openid"
		  });
		  
	  }
	//...
}
```

**Comment by vsavic** [comment]
I just saw some additional info on startup error:

> ConfigurationException
> appHost.Config.WebHostUrl must be set to use the Identity Server User Login plugin so that the service can sent it's full http://url:port to the Identity Server User Login
> 
> [Object: 2018-10-23 2:20:15 PM]:\n[REQUEST:]\nServiceStack.Authentication.IdentityServer.Exceptions.ConfigurationException: appHost.Config.WebHostUrl must be set to use the Identity Server User Login plugin so that the service can sent it's full http://url:port to the Identity Server User Login\r\n   at ServiceStack.Authentication.IdentityServer.IdentityServerAuthFeature.ValidateCallbackRequirements(IAppHost appHost)\r\n   at ServiceStack.Authentication.IdentityServer.IdentityServerAuthFeature.Register(IAppHost appHost)\r\n   at ServiceStack.ServiceStackHost.LoadPluginsInternal(IPlugin[] plugins)
